site_name: PMCOL Teaching Tool

theme:
  name: material

nav:
  - Project Requirements: index.md
  - User Manual: user-manual.md
  - Software Design: design.md
  - Project Management: project-management.md
  - Teamwork: teamwork.md
  - Meetings: meetings.md

  - Technical Details:
      - API & Supabase: api.md
      - Run Locally: run-local.md
      - Interactions: interface-interactions.md
      - Workflow: ci-cd.md
      - Testing: testing.md
      - AI Pipeline: ai.md
  
  - UX/UI Guidelines:
      - Product & Audience: audience.md
      - UX Principles: principles.md
      - Accessibility & Style: accessibility.md
