site_name: PMCOL Teaching Tool
theme:
  name: material

nav:
  - Project Requirements: index.md
  - Software Design: design.md
  - Project Management: project-management.md
  - Teamwork: teamwork.md
  - Meetings: meetings.md
